### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by jabra98** [juv/vibranceGUI#92]
Hello, I tried to build the project and downloaded the C# workload from the VS installer but I'm getting this error when trying to build the project:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Fody: An unhandled exception occurred:
Exception:
Could not load file or assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
StackTrace:

Server stack trace: 
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
   at System.Reflection.RuntimeMethodInfo.GetParameters()
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at IInnerWeaver.set_Logger(ILogger value)
   at Processor.ExecuteInOwnAppDomain() in c:\TeamCity\buildAgent\work\ed448661dbb30d2e\Fody\Processor.cs:line 149
   at Processor.Inner() in c:\TeamCity\buildAgent\work\ed448661dbb30d2e\Fody\Processor.cs:line 97
   at Processor.Execute() in c:\TeamCity\buildAgent\work\ed448661dbb30d2e\Fody\Processor.cs:line 49
Source:
mscorlib
TargetSite:
Void GetSignature(Void*, Int32, System.RuntimeFieldHandleInternal, System.IRuntimeMethodInfo, System.RuntimeType)
Could not load file or assembly 'Microsoft.Build.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
StackTrace:	vibrance.GUI			
```
Does anyone know how to fix that? I've never used C# before

**Comment by juv** [comment]
Hi,

googling the error message shows a lot of possible solutions regarding some Visual Studio problem. Have you fixed it?
